[build]
command = "npm run build"
publish = "public"

[dev]
autoLaunch = false
framework = "#static"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/build/*"

[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"